import { Metadata } from "next";
import "./globals.css";
import { TheHeader } from "@/components/TheHeader";
import { TheFooter } from "@/components/TheFooter";
import React from "react";

export const metadata: Metadata = {
    title: "Euro 2024",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <link rel="icon" href="/favicon.ico" sizes="any"/>
        <body>
        <TheHeader/>
        <main className="container">{children}</main>
        <TheFooter/>
        </body>
        </html>
    );
}